"""Slack sender module — posts messages to Slack via webhook."""

import requests
import logging
from typing import Optional
from config import Config

logger = logging.getLogger(__name__)


class SlackSender:
    """Send messages to Slack via Incoming Webhook."""

    def __init__(self, webhook_url: str):
        self.webhook_url = webhook_url

    def send_message(self, text: str, title: Optional[str] = None, blocks: Optional[list] = None) -> bool:
        """
        Send a message to Slack.

        Args:
            text: Plain text message
            title: Optional title/header
            blocks: Optional Slack Block Kit blocks for rich formatting

        Returns:
            True if successful, False otherwise
        """
        try:
            if blocks:
                payload = {"blocks": blocks}
            else:
                # Build simple message with optional title
                message = f"*{title}*\n\n{text}" if title else text
                payload = {
                    "text": message,
                    "mrkdwn": True,
                }

            response = requests.post(self.webhook_url, json=payload, timeout=10)
            response.raise_for_status()
            logger.info("Message sent to Slack successfully")
            return True

        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to send message to Slack: {e}")
            return False

    @staticmethod
    def format_email_summary(summary: str, email_count: int) -> list:
        """Format email summary as Slack blocks for rich formatting."""
        return [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*📧 Email Summary*\n_{email_count} emails summarized_",
                },
            },
            {
                "type": "divider",
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": summary,
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by AutoPilot",
                    },
                ],
            },
        ]


# Quick test
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    sender = SlackSender(Config.SLACK_WEBHOOK_URL)
    blocks = SlackSender.format_email_summary("Test summary of emails", 3)
    sender.send_message("Test", blocks=blocks)
